lib: [
  "/Users/ter/dev/diverse/wejay-cli/_esy/default/store/b/wejay_cli-f53ee714/install/default/lib/wejay/META" {"META"}
  "/Users/ter/dev/diverse/wejay-cli/_esy/default/store/b/wejay_cli-f53ee714/install/default/lib/wejay/dune-package" {"dune-package"}
  "/Users/ter/dev/diverse/wejay-cli/_esy/default/store/b/wejay_cli-f53ee714/install/default/lib/wejay/opam" {"opam"}
]
bin: [
  "/Users/ter/dev/diverse/wejay-cli/_esy/default/store/b/wejay_cli-f53ee714/install/default/bin/wejaycli" {"wejaycli"}
]
doc: [
  "/Users/ter/dev/diverse/wejay-cli/_esy/default/store/b/wejay_cli-f53ee714/install/default/doc/wejay/README.md"
]
